// Code generated by Fern. DO NOT EDIT.

package ats_candidates_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	v2 "github.com/merge-api/merge-go-client/v2"
	ats "github.com/merge-api/merge-go-client/v2/ats"
	client "github.com/merge-api/merge-go-client/v2/client"
	option "github.com/merge-api/merge-go-client/v2/option"
	require "github.com/stretchr/testify/require"
	http "net/http"
	testing "testing"
)

func ResetWireMockRequests(
	t *testing.T,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	_, err := http.Post(WiremockAdminURL+"/requests/reset", "application/json", nil)
	require.NoError(t, err)
}

func VerifyRequestCount(
	t *testing.T,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	WiremockAdminURL := "http://localhost:8080/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`"}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestAtsCandidatesListWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &ats.CandidatesListRequest{
		CreatedAfter: merge.Time(
			merge.MustParseDateTime(
				"2024-01-15T09:30:00Z",
			),
		),
		CreatedBefore: merge.Time(
			merge.MustParseDateTime(
				"2024-01-15T09:30:00Z",
			),
		),
		Cursor: merge.String(
			"cD0yMDIxLTAxLTA2KzAzJTNBMjQlM0E1My40MzQzMjYlMkIwMCUzQTAw",
		),
		EmailAddresses: merge.String(
			"email_addresses",
		),
		FirstName: merge.String(
			"first_name",
		),
		IncludeDeletedData: merge.Bool(
			true,
		),
		IncludeRemoteData: merge.Bool(
			true,
		),
		IncludeShellData: merge.Bool(
			true,
		),
		LastName: merge.String(
			"last_name",
		),
		ModifiedAfter: merge.Time(
			merge.MustParseDateTime(
				"2024-01-15T09:30:00Z",
			),
		),
		ModifiedBefore: merge.Time(
			merge.MustParseDateTime(
				"2024-01-15T09:30:00Z",
			),
		),
		PageSize: merge.Int(
			1,
		),
		RemoteId: merge.String(
			"remote_id",
		),
		Tags: merge.String(
			"tags",
		),
	}
	_, invocationErr := client.Ats.Candidates.List(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/ats/v1/candidates", map[string]string{"created_after": "2024-01-15T09:30:00Z", "created_before": "2024-01-15T09:30:00Z", "cursor": "cD0yMDIxLTAxLTA2KzAzJTNBMjQlM0E1My40MzQzMjYlMkIwMCUzQTAw", "email_addresses": "email_addresses", "first_name": "first_name", "include_deleted_data": "true", "include_remote_data": "true", "include_shell_data": "true", "last_name": "last_name", "modified_after": "2024-01-15T09:30:00Z", "modified_before": "2024-01-15T09:30:00Z", "page_size": "1", "remote_id": "remote_id", "tags": "tags"}, 1)
}

func TestAtsCandidatesCreateWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &ats.CandidateEndpointRequest{
		IsDebugMode: merge.Bool(
			true,
		),
		RunAsync: merge.Bool(
			true,
		),
		Model:        &ats.CandidateRequest{},
		RemoteUserId: "remote_user_id",
	}
	_, invocationErr := client.Ats.Candidates.Create(
		context.TODO(),
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/ats/v1/candidates", map[string]string{"is_debug_mode": "true", "run_async": "true"}, 1)
}

func TestAtsCandidatesRetrieveWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &ats.CandidatesRetrieveRequest{
		IncludeRemoteData: merge.Bool(
			true,
		),
		IncludeShellData: merge.Bool(
			true,
		),
	}
	_, invocationErr := client.Ats.Candidates.Retrieve(
		context.TODO(),
		"id",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/ats/v1/candidates/id", map[string]string{"include_remote_data": "true", "include_shell_data": "true"}, 1)
}

func TestAtsCandidatesPartialUpdateWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &ats.PatchedCandidateEndpointRequest{
		IsDebugMode: merge.Bool(
			true,
		),
		RunAsync: merge.Bool(
			true,
		),
		Model:        &ats.PatchedCandidateRequest{},
		RemoteUserId: "remote_user_id",
	}
	_, invocationErr := client.Ats.Candidates.PartialUpdate(
		context.TODO(),
		"id",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "PATCH", "/ats/v1/candidates/id", map[string]string{"is_debug_mode": "true", "run_async": "true"}, 1)
}

func TestAtsCandidatesIgnoreCreateWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	request := &ats.IgnoreCommonModelRequest{
		Reason: &ats.IgnoreCommonModelRequestReason{
			ReasonEnum: ats.ReasonEnumGeneralCustomerRequest,
		},
	}
	invocationErr := client.Ats.Candidates.IgnoreCreate(
		context.TODO(),
		"model_id",
		request,
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "POST", "/ats/v1/candidates/ignore/model_id", nil, 1)
}

func TestAtsCandidatesMetaPatchRetrieveWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.Ats.Candidates.MetaPatchRetrieve(
		context.TODO(),
		"id",
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/ats/v1/candidates/meta/patch/id", nil, 1)
}

func TestAtsCandidatesMetaPostRetrieveWithWireMock(
	t *testing.T,
) {
	ResetWireMockRequests(t)
	WireMockBaseURL := "http://localhost:8080"
	client := client.NewClient(
		option.WithBaseURL(
			WireMockBaseURL,
		),
	)
	_, invocationErr := client.Ats.Candidates.MetaPostRetrieve(
		context.TODO(),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "GET", "/ats/v1/candidates/meta/post", nil, 1)
}
