// Code generated by Fern. DO NOT EDIT.

package ats

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/merge-api/merge-go-client/v2/internal"
	big "math/big"
)

var (
	createFieldMappingRequestFieldExcludeRemoteFieldMetadata = big.NewInt(1 << 0)
	createFieldMappingRequestFieldTargetFieldName            = big.NewInt(1 << 1)
	createFieldMappingRequestFieldTargetFieldDescription     = big.NewInt(1 << 2)
	createFieldMappingRequestFieldRemoteFieldTraversalPath   = big.NewInt(1 << 3)
	createFieldMappingRequestFieldRemoteMethod               = big.NewInt(1 << 4)
	createFieldMappingRequestFieldRemoteUrlPath              = big.NewInt(1 << 5)
	createFieldMappingRequestFieldCommonModelName            = big.NewInt(1 << 6)
)

type CreateFieldMappingRequest struct {
	// If `true`, remote fields metadata is excluded from each field mapping instance (i.e. `remote_fields.remote_key_name` and `remote_fields.schema` will be null). This will increase the speed of the request since these fields require some calculations.
	ExcludeRemoteFieldMetadata *bool `json:"-" url:"exclude_remote_field_metadata,omitempty"`
	// The name of the target field you want this remote field to map to.
	TargetFieldName string `json:"target_field_name" url:"-"`
	// The description of the target field you want this remote field to map to.
	TargetFieldDescription string `json:"target_field_description" url:"-"`
	// The field traversal path of the remote field listed when you hit the GET /remote-fields endpoint.
	RemoteFieldTraversalPath []interface{} `json:"remote_field_traversal_path,omitempty" url:"-"`
	// The method of the remote endpoint where the remote field is coming from.
	RemoteMethod string `json:"remote_method" url:"-"`
	// The path of the remote endpoint where the remote field is coming from.
	RemoteUrlPath string `json:"remote_url_path" url:"-"`
	// The name of the Common Model that the remote field corresponds to in a given category.
	CommonModelName string `json:"common_model_name" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateFieldMappingRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetExcludeRemoteFieldMetadata sets the ExcludeRemoteFieldMetadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateFieldMappingRequest) SetExcludeRemoteFieldMetadata(excludeRemoteFieldMetadata *bool) {
	c.ExcludeRemoteFieldMetadata = excludeRemoteFieldMetadata
	c.require(createFieldMappingRequestFieldExcludeRemoteFieldMetadata)
}

// SetTargetFieldName sets the TargetFieldName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateFieldMappingRequest) SetTargetFieldName(targetFieldName string) {
	c.TargetFieldName = targetFieldName
	c.require(createFieldMappingRequestFieldTargetFieldName)
}

// SetTargetFieldDescription sets the TargetFieldDescription field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateFieldMappingRequest) SetTargetFieldDescription(targetFieldDescription string) {
	c.TargetFieldDescription = targetFieldDescription
	c.require(createFieldMappingRequestFieldTargetFieldDescription)
}

// SetRemoteFieldTraversalPath sets the RemoteFieldTraversalPath field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateFieldMappingRequest) SetRemoteFieldTraversalPath(remoteFieldTraversalPath []interface{}) {
	c.RemoteFieldTraversalPath = remoteFieldTraversalPath
	c.require(createFieldMappingRequestFieldRemoteFieldTraversalPath)
}

// SetRemoteMethod sets the RemoteMethod field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateFieldMappingRequest) SetRemoteMethod(remoteMethod string) {
	c.RemoteMethod = remoteMethod
	c.require(createFieldMappingRequestFieldRemoteMethod)
}

// SetRemoteUrlPath sets the RemoteUrlPath field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateFieldMappingRequest) SetRemoteUrlPath(remoteUrlPath string) {
	c.RemoteUrlPath = remoteUrlPath
	c.require(createFieldMappingRequestFieldRemoteUrlPath)
}

// SetCommonModelName sets the CommonModelName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateFieldMappingRequest) SetCommonModelName(commonModelName string) {
	c.CommonModelName = commonModelName
	c.require(createFieldMappingRequestFieldCommonModelName)
}

var (
	patchedEditFieldMappingRequestFieldRemoteFieldTraversalPath = big.NewInt(1 << 0)
	patchedEditFieldMappingRequestFieldRemoteMethod             = big.NewInt(1 << 1)
	patchedEditFieldMappingRequestFieldRemoteUrlPath            = big.NewInt(1 << 2)
)

type PatchedEditFieldMappingRequest struct {
	// The field traversal path of the remote field listed when you hit the GET /remote-fields endpoint.
	RemoteFieldTraversalPath []interface{} `json:"remote_field_traversal_path,omitempty" url:"-"`
	// The method of the remote endpoint where the remote field is coming from.
	RemoteMethod *string `json:"remote_method,omitempty" url:"-"`
	// The path of the remote endpoint where the remote field is coming from.
	RemoteUrlPath *string `json:"remote_url_path,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PatchedEditFieldMappingRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetRemoteFieldTraversalPath sets the RemoteFieldTraversalPath field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchedEditFieldMappingRequest) SetRemoteFieldTraversalPath(remoteFieldTraversalPath []interface{}) {
	p.RemoteFieldTraversalPath = remoteFieldTraversalPath
	p.require(patchedEditFieldMappingRequestFieldRemoteFieldTraversalPath)
}

// SetRemoteMethod sets the RemoteMethod field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchedEditFieldMappingRequest) SetRemoteMethod(remoteMethod *string) {
	p.RemoteMethod = remoteMethod
	p.require(patchedEditFieldMappingRequestFieldRemoteMethod)
}

// SetRemoteUrlPath sets the RemoteUrlPath field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PatchedEditFieldMappingRequest) SetRemoteUrlPath(remoteUrlPath *string) {
	p.RemoteUrlPath = remoteUrlPath
	p.require(patchedEditFieldMappingRequestFieldRemoteUrlPath)
}

var (
	fieldMappingsRetrieveRequestFieldExcludeRemoteFieldMetadata = big.NewInt(1 << 0)
)

type FieldMappingsRetrieveRequest struct {
	// If `true`, remote fields metadata is excluded from each field mapping instance (i.e. `remote_fields.remote_key_name` and `remote_fields.schema` will be null). This will increase the speed of the request since these fields require some calculations.
	ExcludeRemoteFieldMetadata *bool `json:"-" url:"exclude_remote_field_metadata,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (f *FieldMappingsRetrieveRequest) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetExcludeRemoteFieldMetadata sets the ExcludeRemoteFieldMetadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingsRetrieveRequest) SetExcludeRemoteFieldMetadata(excludeRemoteFieldMetadata *bool) {
	f.ExcludeRemoteFieldMetadata = excludeRemoteFieldMetadata
	f.require(fieldMappingsRetrieveRequestFieldExcludeRemoteFieldMetadata)
}

var (
	remoteFieldsRetrieveRequestFieldCommonModels         = big.NewInt(1 << 0)
	remoteFieldsRetrieveRequestFieldIncludeExampleValues = big.NewInt(1 << 1)
)

type RemoteFieldsRetrieveRequest struct {
	// A comma seperated list of Common Model names. If included, will only return Remote Fields for those Common Models.
	CommonModels *string `json:"-" url:"common_models,omitempty"`
	// If true, will include example values, where available, for remote fields in the 3rd party platform. These examples come from active data from your customers.
	IncludeExampleValues *string `json:"-" url:"include_example_values,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RemoteFieldsRetrieveRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetCommonModels sets the CommonModels field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldsRetrieveRequest) SetCommonModels(commonModels *string) {
	r.CommonModels = commonModels
	r.require(remoteFieldsRetrieveRequestFieldCommonModels)
}

// SetIncludeExampleValues sets the IncludeExampleValues field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldsRetrieveRequest) SetIncludeExampleValues(includeExampleValues *string) {
	r.IncludeExampleValues = includeExampleValues
	r.require(remoteFieldsRetrieveRequestFieldIncludeExampleValues)
}

var (
	advancedMetadataFieldId           = big.NewInt(1 << 0)
	advancedMetadataFieldDisplayName  = big.NewInt(1 << 1)
	advancedMetadataFieldDescription  = big.NewInt(1 << 2)
	advancedMetadataFieldIsRequired   = big.NewInt(1 << 3)
	advancedMetadataFieldIsCustom     = big.NewInt(1 << 4)
	advancedMetadataFieldFieldChoices = big.NewInt(1 << 5)
)

type AdvancedMetadata struct {
	Id           string        `json:"id" url:"id"`
	DisplayName  *string       `json:"display_name,omitempty" url:"display_name,omitempty"`
	Description  *string       `json:"description,omitempty" url:"description,omitempty"`
	IsRequired   *bool         `json:"is_required,omitempty" url:"is_required,omitempty"`
	IsCustom     *bool         `json:"is_custom,omitempty" url:"is_custom,omitempty"`
	FieldChoices []interface{} `json:"field_choices,omitempty" url:"field_choices,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *AdvancedMetadata) GetId() string {
	if a == nil {
		return ""
	}
	return a.Id
}

func (a *AdvancedMetadata) GetDisplayName() *string {
	if a == nil {
		return nil
	}
	return a.DisplayName
}

func (a *AdvancedMetadata) GetDescription() *string {
	if a == nil {
		return nil
	}
	return a.Description
}

func (a *AdvancedMetadata) GetIsRequired() *bool {
	if a == nil {
		return nil
	}
	return a.IsRequired
}

func (a *AdvancedMetadata) GetIsCustom() *bool {
	if a == nil {
		return nil
	}
	return a.IsCustom
}

func (a *AdvancedMetadata) GetFieldChoices() []interface{} {
	if a == nil {
		return nil
	}
	return a.FieldChoices
}

func (a *AdvancedMetadata) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *AdvancedMetadata) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AdvancedMetadata) SetId(id string) {
	a.Id = id
	a.require(advancedMetadataFieldId)
}

// SetDisplayName sets the DisplayName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AdvancedMetadata) SetDisplayName(displayName *string) {
	a.DisplayName = displayName
	a.require(advancedMetadataFieldDisplayName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AdvancedMetadata) SetDescription(description *string) {
	a.Description = description
	a.require(advancedMetadataFieldDescription)
}

// SetIsRequired sets the IsRequired field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AdvancedMetadata) SetIsRequired(isRequired *bool) {
	a.IsRequired = isRequired
	a.require(advancedMetadataFieldIsRequired)
}

// SetIsCustom sets the IsCustom field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AdvancedMetadata) SetIsCustom(isCustom *bool) {
	a.IsCustom = isCustom
	a.require(advancedMetadataFieldIsCustom)
}

// SetFieldChoices sets the FieldChoices field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *AdvancedMetadata) SetFieldChoices(fieldChoices []interface{}) {
	a.FieldChoices = fieldChoices
	a.require(advancedMetadataFieldFieldChoices)
}

func (a *AdvancedMetadata) UnmarshalJSON(data []byte) error {
	type unmarshaler AdvancedMetadata
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = AdvancedMetadata(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *AdvancedMetadata) MarshalJSON() ([]byte, error) {
	type embed AdvancedMetadata
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *AdvancedMetadata) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	externalTargetFieldApiFieldName        = big.NewInt(1 << 0)
	externalTargetFieldApiFieldDescription = big.NewInt(1 << 1)
	externalTargetFieldApiFieldIsMapped    = big.NewInt(1 << 2)
)

type ExternalTargetFieldApi struct {
	Name        *string `json:"name,omitempty" url:"name,omitempty"`
	Description *string `json:"description,omitempty" url:"description,omitempty"`
	IsMapped    *string `json:"is_mapped,omitempty" url:"is_mapped,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *ExternalTargetFieldApi) GetName() *string {
	if e == nil {
		return nil
	}
	return e.Name
}

func (e *ExternalTargetFieldApi) GetDescription() *string {
	if e == nil {
		return nil
	}
	return e.Description
}

func (e *ExternalTargetFieldApi) GetIsMapped() *string {
	if e == nil {
		return nil
	}
	return e.IsMapped
}

func (e *ExternalTargetFieldApi) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *ExternalTargetFieldApi) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalTargetFieldApi) SetName(name *string) {
	e.Name = name
	e.require(externalTargetFieldApiFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalTargetFieldApi) SetDescription(description *string) {
	e.Description = description
	e.require(externalTargetFieldApiFieldDescription)
}

// SetIsMapped sets the IsMapped field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalTargetFieldApi) SetIsMapped(isMapped *string) {
	e.IsMapped = isMapped
	e.require(externalTargetFieldApiFieldIsMapped)
}

func (e *ExternalTargetFieldApi) UnmarshalJSON(data []byte) error {
	type unmarshaler ExternalTargetFieldApi
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = ExternalTargetFieldApi(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *ExternalTargetFieldApi) MarshalJSON() ([]byte, error) {
	type embed ExternalTargetFieldApi
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *ExternalTargetFieldApi) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	externalTargetFieldApiResponseFieldActivity           = big.NewInt(1 << 0)
	externalTargetFieldApiResponseFieldApplication        = big.NewInt(1 << 1)
	externalTargetFieldApiResponseFieldAttachment         = big.NewInt(1 << 2)
	externalTargetFieldApiResponseFieldCandidate          = big.NewInt(1 << 3)
	externalTargetFieldApiResponseFieldDepartment         = big.NewInt(1 << 4)
	externalTargetFieldApiResponseFieldEeoc               = big.NewInt(1 << 5)
	externalTargetFieldApiResponseFieldScheduledInterview = big.NewInt(1 << 6)
	externalTargetFieldApiResponseFieldJob                = big.NewInt(1 << 7)
	externalTargetFieldApiResponseFieldJobPosting         = big.NewInt(1 << 8)
	externalTargetFieldApiResponseFieldJobInterviewStage  = big.NewInt(1 << 9)
	externalTargetFieldApiResponseFieldOffer              = big.NewInt(1 << 10)
	externalTargetFieldApiResponseFieldOffice             = big.NewInt(1 << 11)
	externalTargetFieldApiResponseFieldRejectReason       = big.NewInt(1 << 12)
	externalTargetFieldApiResponseFieldScorecard          = big.NewInt(1 << 13)
	externalTargetFieldApiResponseFieldTag                = big.NewInt(1 << 14)
	externalTargetFieldApiResponseFieldRemoteUser         = big.NewInt(1 << 15)
)

type ExternalTargetFieldApiResponse struct {
	Activity           []*ExternalTargetFieldApi `json:"Activity,omitempty" url:"Activity,omitempty"`
	Application        []*ExternalTargetFieldApi `json:"Application,omitempty" url:"Application,omitempty"`
	Attachment         []*ExternalTargetFieldApi `json:"Attachment,omitempty" url:"Attachment,omitempty"`
	Candidate          []*ExternalTargetFieldApi `json:"Candidate,omitempty" url:"Candidate,omitempty"`
	Department         []*ExternalTargetFieldApi `json:"Department,omitempty" url:"Department,omitempty"`
	Eeoc               []*ExternalTargetFieldApi `json:"EEOC,omitempty" url:"EEOC,omitempty"`
	ScheduledInterview []*ExternalTargetFieldApi `json:"ScheduledInterview,omitempty" url:"ScheduledInterview,omitempty"`
	Job                []*ExternalTargetFieldApi `json:"Job,omitempty" url:"Job,omitempty"`
	JobPosting         []*ExternalTargetFieldApi `json:"JobPosting,omitempty" url:"JobPosting,omitempty"`
	JobInterviewStage  []*ExternalTargetFieldApi `json:"JobInterviewStage,omitempty" url:"JobInterviewStage,omitempty"`
	Offer              []*ExternalTargetFieldApi `json:"Offer,omitempty" url:"Offer,omitempty"`
	Office             []*ExternalTargetFieldApi `json:"Office,omitempty" url:"Office,omitempty"`
	RejectReason       []*ExternalTargetFieldApi `json:"RejectReason,omitempty" url:"RejectReason,omitempty"`
	Scorecard          []*ExternalTargetFieldApi `json:"Scorecard,omitempty" url:"Scorecard,omitempty"`
	Tag                []*ExternalTargetFieldApi `json:"Tag,omitempty" url:"Tag,omitempty"`
	RemoteUser         []*ExternalTargetFieldApi `json:"RemoteUser,omitempty" url:"RemoteUser,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (e *ExternalTargetFieldApiResponse) GetActivity() []*ExternalTargetFieldApi {
	if e == nil {
		return nil
	}
	return e.Activity
}

func (e *ExternalTargetFieldApiResponse) GetApplication() []*ExternalTargetFieldApi {
	if e == nil {
		return nil
	}
	return e.Application
}

func (e *ExternalTargetFieldApiResponse) GetAttachment() []*ExternalTargetFieldApi {
	if e == nil {
		return nil
	}
	return e.Attachment
}

func (e *ExternalTargetFieldApiResponse) GetCandidate() []*ExternalTargetFieldApi {
	if e == nil {
		return nil
	}
	return e.Candidate
}

func (e *ExternalTargetFieldApiResponse) GetDepartment() []*ExternalTargetFieldApi {
	if e == nil {
		return nil
	}
	return e.Department
}

func (e *ExternalTargetFieldApiResponse) GetEeoc() []*ExternalTargetFieldApi {
	if e == nil {
		return nil
	}
	return e.Eeoc
}

func (e *ExternalTargetFieldApiResponse) GetScheduledInterview() []*ExternalTargetFieldApi {
	if e == nil {
		return nil
	}
	return e.ScheduledInterview
}

func (e *ExternalTargetFieldApiResponse) GetJob() []*ExternalTargetFieldApi {
	if e == nil {
		return nil
	}
	return e.Job
}

func (e *ExternalTargetFieldApiResponse) GetJobPosting() []*ExternalTargetFieldApi {
	if e == nil {
		return nil
	}
	return e.JobPosting
}

func (e *ExternalTargetFieldApiResponse) GetJobInterviewStage() []*ExternalTargetFieldApi {
	if e == nil {
		return nil
	}
	return e.JobInterviewStage
}

func (e *ExternalTargetFieldApiResponse) GetOffer() []*ExternalTargetFieldApi {
	if e == nil {
		return nil
	}
	return e.Offer
}

func (e *ExternalTargetFieldApiResponse) GetOffice() []*ExternalTargetFieldApi {
	if e == nil {
		return nil
	}
	return e.Office
}

func (e *ExternalTargetFieldApiResponse) GetRejectReason() []*ExternalTargetFieldApi {
	if e == nil {
		return nil
	}
	return e.RejectReason
}

func (e *ExternalTargetFieldApiResponse) GetScorecard() []*ExternalTargetFieldApi {
	if e == nil {
		return nil
	}
	return e.Scorecard
}

func (e *ExternalTargetFieldApiResponse) GetTag() []*ExternalTargetFieldApi {
	if e == nil {
		return nil
	}
	return e.Tag
}

func (e *ExternalTargetFieldApiResponse) GetRemoteUser() []*ExternalTargetFieldApi {
	if e == nil {
		return nil
	}
	return e.RemoteUser
}

func (e *ExternalTargetFieldApiResponse) GetExtraProperties() map[string]interface{} {
	return e.extraProperties
}

func (e *ExternalTargetFieldApiResponse) require(field *big.Int) {
	if e.explicitFields == nil {
		e.explicitFields = big.NewInt(0)
	}
	e.explicitFields.Or(e.explicitFields, field)
}

// SetActivity sets the Activity field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalTargetFieldApiResponse) SetActivity(activity []*ExternalTargetFieldApi) {
	e.Activity = activity
	e.require(externalTargetFieldApiResponseFieldActivity)
}

// SetApplication sets the Application field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalTargetFieldApiResponse) SetApplication(application []*ExternalTargetFieldApi) {
	e.Application = application
	e.require(externalTargetFieldApiResponseFieldApplication)
}

// SetAttachment sets the Attachment field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalTargetFieldApiResponse) SetAttachment(attachment []*ExternalTargetFieldApi) {
	e.Attachment = attachment
	e.require(externalTargetFieldApiResponseFieldAttachment)
}

// SetCandidate sets the Candidate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalTargetFieldApiResponse) SetCandidate(candidate []*ExternalTargetFieldApi) {
	e.Candidate = candidate
	e.require(externalTargetFieldApiResponseFieldCandidate)
}

// SetDepartment sets the Department field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalTargetFieldApiResponse) SetDepartment(department []*ExternalTargetFieldApi) {
	e.Department = department
	e.require(externalTargetFieldApiResponseFieldDepartment)
}

// SetEeoc sets the Eeoc field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalTargetFieldApiResponse) SetEeoc(eeoc []*ExternalTargetFieldApi) {
	e.Eeoc = eeoc
	e.require(externalTargetFieldApiResponseFieldEeoc)
}

// SetScheduledInterview sets the ScheduledInterview field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalTargetFieldApiResponse) SetScheduledInterview(scheduledInterview []*ExternalTargetFieldApi) {
	e.ScheduledInterview = scheduledInterview
	e.require(externalTargetFieldApiResponseFieldScheduledInterview)
}

// SetJob sets the Job field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalTargetFieldApiResponse) SetJob(job []*ExternalTargetFieldApi) {
	e.Job = job
	e.require(externalTargetFieldApiResponseFieldJob)
}

// SetJobPosting sets the JobPosting field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalTargetFieldApiResponse) SetJobPosting(jobPosting []*ExternalTargetFieldApi) {
	e.JobPosting = jobPosting
	e.require(externalTargetFieldApiResponseFieldJobPosting)
}

// SetJobInterviewStage sets the JobInterviewStage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalTargetFieldApiResponse) SetJobInterviewStage(jobInterviewStage []*ExternalTargetFieldApi) {
	e.JobInterviewStage = jobInterviewStage
	e.require(externalTargetFieldApiResponseFieldJobInterviewStage)
}

// SetOffer sets the Offer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalTargetFieldApiResponse) SetOffer(offer []*ExternalTargetFieldApi) {
	e.Offer = offer
	e.require(externalTargetFieldApiResponseFieldOffer)
}

// SetOffice sets the Office field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalTargetFieldApiResponse) SetOffice(office []*ExternalTargetFieldApi) {
	e.Office = office
	e.require(externalTargetFieldApiResponseFieldOffice)
}

// SetRejectReason sets the RejectReason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalTargetFieldApiResponse) SetRejectReason(rejectReason []*ExternalTargetFieldApi) {
	e.RejectReason = rejectReason
	e.require(externalTargetFieldApiResponseFieldRejectReason)
}

// SetScorecard sets the Scorecard field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalTargetFieldApiResponse) SetScorecard(scorecard []*ExternalTargetFieldApi) {
	e.Scorecard = scorecard
	e.require(externalTargetFieldApiResponseFieldScorecard)
}

// SetTag sets the Tag field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalTargetFieldApiResponse) SetTag(tag []*ExternalTargetFieldApi) {
	e.Tag = tag
	e.require(externalTargetFieldApiResponseFieldTag)
}

// SetRemoteUser sets the RemoteUser field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (e *ExternalTargetFieldApiResponse) SetRemoteUser(remoteUser []*ExternalTargetFieldApi) {
	e.RemoteUser = remoteUser
	e.require(externalTargetFieldApiResponseFieldRemoteUser)
}

func (e *ExternalTargetFieldApiResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ExternalTargetFieldApiResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*e = ExternalTargetFieldApiResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *e)
	if err != nil {
		return err
	}
	e.extraProperties = extraProperties
	e.rawJSON = json.RawMessage(data)
	return nil
}

func (e *ExternalTargetFieldApiResponse) MarshalJSON() ([]byte, error) {
	type embed ExternalTargetFieldApiResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*e),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, e.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (e *ExternalTargetFieldApiResponse) String() string {
	if len(e.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(e.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

var (
	fieldMappingApiInstanceFieldId                = big.NewInt(1 << 0)
	fieldMappingApiInstanceFieldIsIntegrationWide = big.NewInt(1 << 1)
	fieldMappingApiInstanceFieldTargetField       = big.NewInt(1 << 2)
	fieldMappingApiInstanceFieldRemoteField       = big.NewInt(1 << 3)
)

type FieldMappingApiInstance struct {
	Id                *string                             `json:"id,omitempty" url:"id,omitempty"`
	IsIntegrationWide *bool                               `json:"is_integration_wide,omitempty" url:"is_integration_wide,omitempty"`
	TargetField       *FieldMappingApiInstanceTargetField `json:"target_field,omitempty" url:"target_field,omitempty"`
	RemoteField       *FieldMappingApiInstanceRemoteField `json:"remote_field,omitempty" url:"remote_field,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FieldMappingApiInstance) GetId() *string {
	if f == nil {
		return nil
	}
	return f.Id
}

func (f *FieldMappingApiInstance) GetIsIntegrationWide() *bool {
	if f == nil {
		return nil
	}
	return f.IsIntegrationWide
}

func (f *FieldMappingApiInstance) GetTargetField() *FieldMappingApiInstanceTargetField {
	if f == nil {
		return nil
	}
	return f.TargetField
}

func (f *FieldMappingApiInstance) GetRemoteField() *FieldMappingApiInstanceRemoteField {
	if f == nil {
		return nil
	}
	return f.RemoteField
}

func (f *FieldMappingApiInstance) GetExtraProperties() map[string]interface{} {
	return f.extraProperties
}

func (f *FieldMappingApiInstance) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetId sets the Id field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstance) SetId(id *string) {
	f.Id = id
	f.require(fieldMappingApiInstanceFieldId)
}

// SetIsIntegrationWide sets the IsIntegrationWide field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstance) SetIsIntegrationWide(isIntegrationWide *bool) {
	f.IsIntegrationWide = isIntegrationWide
	f.require(fieldMappingApiInstanceFieldIsIntegrationWide)
}

// SetTargetField sets the TargetField field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstance) SetTargetField(targetField *FieldMappingApiInstanceTargetField) {
	f.TargetField = targetField
	f.require(fieldMappingApiInstanceFieldTargetField)
}

// SetRemoteField sets the RemoteField field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstance) SetRemoteField(remoteField *FieldMappingApiInstanceRemoteField) {
	f.RemoteField = remoteField
	f.require(fieldMappingApiInstanceFieldRemoteField)
}

func (f *FieldMappingApiInstance) UnmarshalJSON(data []byte) error {
	type unmarshaler FieldMappingApiInstance
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FieldMappingApiInstance(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FieldMappingApiInstance) MarshalJSON() ([]byte, error) {
	type embed FieldMappingApiInstance
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FieldMappingApiInstance) String() string {
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	fieldMappingApiInstanceRemoteFieldFieldRemoteKeyName      = big.NewInt(1 << 0)
	fieldMappingApiInstanceRemoteFieldFieldSchema             = big.NewInt(1 << 1)
	fieldMappingApiInstanceRemoteFieldFieldRemoteEndpointInfo = big.NewInt(1 << 2)
)

type FieldMappingApiInstanceRemoteField struct {
	RemoteKeyName      *string                                               `json:"remote_key_name,omitempty" url:"remote_key_name,omitempty"`
	Schema             map[string]interface{}                                `json:"schema,omitempty" url:"schema,omitempty"`
	RemoteEndpointInfo *FieldMappingApiInstanceRemoteFieldRemoteEndpointInfo `json:"remote_endpoint_info" url:"remote_endpoint_info"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FieldMappingApiInstanceRemoteField) GetRemoteKeyName() *string {
	if f == nil {
		return nil
	}
	return f.RemoteKeyName
}

func (f *FieldMappingApiInstanceRemoteField) GetSchema() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.Schema
}

func (f *FieldMappingApiInstanceRemoteField) GetRemoteEndpointInfo() *FieldMappingApiInstanceRemoteFieldRemoteEndpointInfo {
	if f == nil {
		return nil
	}
	return f.RemoteEndpointInfo
}

func (f *FieldMappingApiInstanceRemoteField) GetExtraProperties() map[string]interface{} {
	return f.extraProperties
}

func (f *FieldMappingApiInstanceRemoteField) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetRemoteKeyName sets the RemoteKeyName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceRemoteField) SetRemoteKeyName(remoteKeyName *string) {
	f.RemoteKeyName = remoteKeyName
	f.require(fieldMappingApiInstanceRemoteFieldFieldRemoteKeyName)
}

// SetSchema sets the Schema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceRemoteField) SetSchema(schema map[string]interface{}) {
	f.Schema = schema
	f.require(fieldMappingApiInstanceRemoteFieldFieldSchema)
}

// SetRemoteEndpointInfo sets the RemoteEndpointInfo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceRemoteField) SetRemoteEndpointInfo(remoteEndpointInfo *FieldMappingApiInstanceRemoteFieldRemoteEndpointInfo) {
	f.RemoteEndpointInfo = remoteEndpointInfo
	f.require(fieldMappingApiInstanceRemoteFieldFieldRemoteEndpointInfo)
}

func (f *FieldMappingApiInstanceRemoteField) UnmarshalJSON(data []byte) error {
	type unmarshaler FieldMappingApiInstanceRemoteField
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FieldMappingApiInstanceRemoteField(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FieldMappingApiInstanceRemoteField) MarshalJSON() ([]byte, error) {
	type embed FieldMappingApiInstanceRemoteField
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FieldMappingApiInstanceRemoteField) String() string {
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	fieldMappingApiInstanceRemoteFieldRemoteEndpointInfoFieldMethod             = big.NewInt(1 << 0)
	fieldMappingApiInstanceRemoteFieldRemoteEndpointInfoFieldUrlPath            = big.NewInt(1 << 1)
	fieldMappingApiInstanceRemoteFieldRemoteEndpointInfoFieldFieldTraversalPath = big.NewInt(1 << 2)
)

type FieldMappingApiInstanceRemoteFieldRemoteEndpointInfo struct {
	Method             *string  `json:"method,omitempty" url:"method,omitempty"`
	UrlPath            *string  `json:"url_path,omitempty" url:"url_path,omitempty"`
	FieldTraversalPath []string `json:"field_traversal_path,omitempty" url:"field_traversal_path,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FieldMappingApiInstanceRemoteFieldRemoteEndpointInfo) GetMethod() *string {
	if f == nil {
		return nil
	}
	return f.Method
}

func (f *FieldMappingApiInstanceRemoteFieldRemoteEndpointInfo) GetUrlPath() *string {
	if f == nil {
		return nil
	}
	return f.UrlPath
}

func (f *FieldMappingApiInstanceRemoteFieldRemoteEndpointInfo) GetFieldTraversalPath() []string {
	if f == nil {
		return nil
	}
	return f.FieldTraversalPath
}

func (f *FieldMappingApiInstanceRemoteFieldRemoteEndpointInfo) GetExtraProperties() map[string]interface{} {
	return f.extraProperties
}

func (f *FieldMappingApiInstanceRemoteFieldRemoteEndpointInfo) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetMethod sets the Method field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceRemoteFieldRemoteEndpointInfo) SetMethod(method *string) {
	f.Method = method
	f.require(fieldMappingApiInstanceRemoteFieldRemoteEndpointInfoFieldMethod)
}

// SetUrlPath sets the UrlPath field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceRemoteFieldRemoteEndpointInfo) SetUrlPath(urlPath *string) {
	f.UrlPath = urlPath
	f.require(fieldMappingApiInstanceRemoteFieldRemoteEndpointInfoFieldUrlPath)
}

// SetFieldTraversalPath sets the FieldTraversalPath field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceRemoteFieldRemoteEndpointInfo) SetFieldTraversalPath(fieldTraversalPath []string) {
	f.FieldTraversalPath = fieldTraversalPath
	f.require(fieldMappingApiInstanceRemoteFieldRemoteEndpointInfoFieldFieldTraversalPath)
}

func (f *FieldMappingApiInstanceRemoteFieldRemoteEndpointInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler FieldMappingApiInstanceRemoteFieldRemoteEndpointInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FieldMappingApiInstanceRemoteFieldRemoteEndpointInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FieldMappingApiInstanceRemoteFieldRemoteEndpointInfo) MarshalJSON() ([]byte, error) {
	type embed FieldMappingApiInstanceRemoteFieldRemoteEndpointInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FieldMappingApiInstanceRemoteFieldRemoteEndpointInfo) String() string {
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	fieldMappingApiInstanceResponseFieldActivity           = big.NewInt(1 << 0)
	fieldMappingApiInstanceResponseFieldApplication        = big.NewInt(1 << 1)
	fieldMappingApiInstanceResponseFieldAttachment         = big.NewInt(1 << 2)
	fieldMappingApiInstanceResponseFieldCandidate          = big.NewInt(1 << 3)
	fieldMappingApiInstanceResponseFieldDepartment         = big.NewInt(1 << 4)
	fieldMappingApiInstanceResponseFieldEeoc               = big.NewInt(1 << 5)
	fieldMappingApiInstanceResponseFieldScheduledInterview = big.NewInt(1 << 6)
	fieldMappingApiInstanceResponseFieldJob                = big.NewInt(1 << 7)
	fieldMappingApiInstanceResponseFieldJobPosting         = big.NewInt(1 << 8)
	fieldMappingApiInstanceResponseFieldJobInterviewStage  = big.NewInt(1 << 9)
	fieldMappingApiInstanceResponseFieldOffer              = big.NewInt(1 << 10)
	fieldMappingApiInstanceResponseFieldOffice             = big.NewInt(1 << 11)
	fieldMappingApiInstanceResponseFieldRejectReason       = big.NewInt(1 << 12)
	fieldMappingApiInstanceResponseFieldScorecard          = big.NewInt(1 << 13)
	fieldMappingApiInstanceResponseFieldTag                = big.NewInt(1 << 14)
	fieldMappingApiInstanceResponseFieldRemoteUser         = big.NewInt(1 << 15)
)

type FieldMappingApiInstanceResponse struct {
	Activity           []*FieldMappingApiInstance `json:"Activity,omitempty" url:"Activity,omitempty"`
	Application        []*FieldMappingApiInstance `json:"Application,omitempty" url:"Application,omitempty"`
	Attachment         []*FieldMappingApiInstance `json:"Attachment,omitempty" url:"Attachment,omitempty"`
	Candidate          []*FieldMappingApiInstance `json:"Candidate,omitempty" url:"Candidate,omitempty"`
	Department         []*FieldMappingApiInstance `json:"Department,omitempty" url:"Department,omitempty"`
	Eeoc               []*FieldMappingApiInstance `json:"EEOC,omitempty" url:"EEOC,omitempty"`
	ScheduledInterview []*FieldMappingApiInstance `json:"ScheduledInterview,omitempty" url:"ScheduledInterview,omitempty"`
	Job                []*FieldMappingApiInstance `json:"Job,omitempty" url:"Job,omitempty"`
	JobPosting         []*FieldMappingApiInstance `json:"JobPosting,omitempty" url:"JobPosting,omitempty"`
	JobInterviewStage  []*FieldMappingApiInstance `json:"JobInterviewStage,omitempty" url:"JobInterviewStage,omitempty"`
	Offer              []*FieldMappingApiInstance `json:"Offer,omitempty" url:"Offer,omitempty"`
	Office             []*FieldMappingApiInstance `json:"Office,omitempty" url:"Office,omitempty"`
	RejectReason       []*FieldMappingApiInstance `json:"RejectReason,omitempty" url:"RejectReason,omitempty"`
	Scorecard          []*FieldMappingApiInstance `json:"Scorecard,omitempty" url:"Scorecard,omitempty"`
	Tag                []*FieldMappingApiInstance `json:"Tag,omitempty" url:"Tag,omitempty"`
	RemoteUser         []*FieldMappingApiInstance `json:"RemoteUser,omitempty" url:"RemoteUser,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FieldMappingApiInstanceResponse) GetActivity() []*FieldMappingApiInstance {
	if f == nil {
		return nil
	}
	return f.Activity
}

func (f *FieldMappingApiInstanceResponse) GetApplication() []*FieldMappingApiInstance {
	if f == nil {
		return nil
	}
	return f.Application
}

func (f *FieldMappingApiInstanceResponse) GetAttachment() []*FieldMappingApiInstance {
	if f == nil {
		return nil
	}
	return f.Attachment
}

func (f *FieldMappingApiInstanceResponse) GetCandidate() []*FieldMappingApiInstance {
	if f == nil {
		return nil
	}
	return f.Candidate
}

func (f *FieldMappingApiInstanceResponse) GetDepartment() []*FieldMappingApiInstance {
	if f == nil {
		return nil
	}
	return f.Department
}

func (f *FieldMappingApiInstanceResponse) GetEeoc() []*FieldMappingApiInstance {
	if f == nil {
		return nil
	}
	return f.Eeoc
}

func (f *FieldMappingApiInstanceResponse) GetScheduledInterview() []*FieldMappingApiInstance {
	if f == nil {
		return nil
	}
	return f.ScheduledInterview
}

func (f *FieldMappingApiInstanceResponse) GetJob() []*FieldMappingApiInstance {
	if f == nil {
		return nil
	}
	return f.Job
}

func (f *FieldMappingApiInstanceResponse) GetJobPosting() []*FieldMappingApiInstance {
	if f == nil {
		return nil
	}
	return f.JobPosting
}

func (f *FieldMappingApiInstanceResponse) GetJobInterviewStage() []*FieldMappingApiInstance {
	if f == nil {
		return nil
	}
	return f.JobInterviewStage
}

func (f *FieldMappingApiInstanceResponse) GetOffer() []*FieldMappingApiInstance {
	if f == nil {
		return nil
	}
	return f.Offer
}

func (f *FieldMappingApiInstanceResponse) GetOffice() []*FieldMappingApiInstance {
	if f == nil {
		return nil
	}
	return f.Office
}

func (f *FieldMappingApiInstanceResponse) GetRejectReason() []*FieldMappingApiInstance {
	if f == nil {
		return nil
	}
	return f.RejectReason
}

func (f *FieldMappingApiInstanceResponse) GetScorecard() []*FieldMappingApiInstance {
	if f == nil {
		return nil
	}
	return f.Scorecard
}

func (f *FieldMappingApiInstanceResponse) GetTag() []*FieldMappingApiInstance {
	if f == nil {
		return nil
	}
	return f.Tag
}

func (f *FieldMappingApiInstanceResponse) GetRemoteUser() []*FieldMappingApiInstance {
	if f == nil {
		return nil
	}
	return f.RemoteUser
}

func (f *FieldMappingApiInstanceResponse) GetExtraProperties() map[string]interface{} {
	return f.extraProperties
}

func (f *FieldMappingApiInstanceResponse) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetActivity sets the Activity field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceResponse) SetActivity(activity []*FieldMappingApiInstance) {
	f.Activity = activity
	f.require(fieldMappingApiInstanceResponseFieldActivity)
}

// SetApplication sets the Application field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceResponse) SetApplication(application []*FieldMappingApiInstance) {
	f.Application = application
	f.require(fieldMappingApiInstanceResponseFieldApplication)
}

// SetAttachment sets the Attachment field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceResponse) SetAttachment(attachment []*FieldMappingApiInstance) {
	f.Attachment = attachment
	f.require(fieldMappingApiInstanceResponseFieldAttachment)
}

// SetCandidate sets the Candidate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceResponse) SetCandidate(candidate []*FieldMappingApiInstance) {
	f.Candidate = candidate
	f.require(fieldMappingApiInstanceResponseFieldCandidate)
}

// SetDepartment sets the Department field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceResponse) SetDepartment(department []*FieldMappingApiInstance) {
	f.Department = department
	f.require(fieldMappingApiInstanceResponseFieldDepartment)
}

// SetEeoc sets the Eeoc field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceResponse) SetEeoc(eeoc []*FieldMappingApiInstance) {
	f.Eeoc = eeoc
	f.require(fieldMappingApiInstanceResponseFieldEeoc)
}

// SetScheduledInterview sets the ScheduledInterview field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceResponse) SetScheduledInterview(scheduledInterview []*FieldMappingApiInstance) {
	f.ScheduledInterview = scheduledInterview
	f.require(fieldMappingApiInstanceResponseFieldScheduledInterview)
}

// SetJob sets the Job field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceResponse) SetJob(job []*FieldMappingApiInstance) {
	f.Job = job
	f.require(fieldMappingApiInstanceResponseFieldJob)
}

// SetJobPosting sets the JobPosting field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceResponse) SetJobPosting(jobPosting []*FieldMappingApiInstance) {
	f.JobPosting = jobPosting
	f.require(fieldMappingApiInstanceResponseFieldJobPosting)
}

// SetJobInterviewStage sets the JobInterviewStage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceResponse) SetJobInterviewStage(jobInterviewStage []*FieldMappingApiInstance) {
	f.JobInterviewStage = jobInterviewStage
	f.require(fieldMappingApiInstanceResponseFieldJobInterviewStage)
}

// SetOffer sets the Offer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceResponse) SetOffer(offer []*FieldMappingApiInstance) {
	f.Offer = offer
	f.require(fieldMappingApiInstanceResponseFieldOffer)
}

// SetOffice sets the Office field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceResponse) SetOffice(office []*FieldMappingApiInstance) {
	f.Office = office
	f.require(fieldMappingApiInstanceResponseFieldOffice)
}

// SetRejectReason sets the RejectReason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceResponse) SetRejectReason(rejectReason []*FieldMappingApiInstance) {
	f.RejectReason = rejectReason
	f.require(fieldMappingApiInstanceResponseFieldRejectReason)
}

// SetScorecard sets the Scorecard field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceResponse) SetScorecard(scorecard []*FieldMappingApiInstance) {
	f.Scorecard = scorecard
	f.require(fieldMappingApiInstanceResponseFieldScorecard)
}

// SetTag sets the Tag field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceResponse) SetTag(tag []*FieldMappingApiInstance) {
	f.Tag = tag
	f.require(fieldMappingApiInstanceResponseFieldTag)
}

// SetRemoteUser sets the RemoteUser field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceResponse) SetRemoteUser(remoteUser []*FieldMappingApiInstance) {
	f.RemoteUser = remoteUser
	f.require(fieldMappingApiInstanceResponseFieldRemoteUser)
}

func (f *FieldMappingApiInstanceResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler FieldMappingApiInstanceResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FieldMappingApiInstanceResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FieldMappingApiInstanceResponse) MarshalJSON() ([]byte, error) {
	type embed FieldMappingApiInstanceResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FieldMappingApiInstanceResponse) String() string {
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	fieldMappingApiInstanceTargetFieldFieldName               = big.NewInt(1 << 0)
	fieldMappingApiInstanceTargetFieldFieldDescription        = big.NewInt(1 << 1)
	fieldMappingApiInstanceTargetFieldFieldIsOrganizationWide = big.NewInt(1 << 2)
)

type FieldMappingApiInstanceTargetField struct {
	Name               string `json:"name" url:"name"`
	Description        string `json:"description" url:"description"`
	IsOrganizationWide bool   `json:"is_organization_wide" url:"is_organization_wide"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FieldMappingApiInstanceTargetField) GetName() string {
	if f == nil {
		return ""
	}
	return f.Name
}

func (f *FieldMappingApiInstanceTargetField) GetDescription() string {
	if f == nil {
		return ""
	}
	return f.Description
}

func (f *FieldMappingApiInstanceTargetField) GetIsOrganizationWide() bool {
	if f == nil {
		return false
	}
	return f.IsOrganizationWide
}

func (f *FieldMappingApiInstanceTargetField) GetExtraProperties() map[string]interface{} {
	return f.extraProperties
}

func (f *FieldMappingApiInstanceTargetField) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceTargetField) SetName(name string) {
	f.Name = name
	f.require(fieldMappingApiInstanceTargetFieldFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceTargetField) SetDescription(description string) {
	f.Description = description
	f.require(fieldMappingApiInstanceTargetFieldFieldDescription)
}

// SetIsOrganizationWide sets the IsOrganizationWide field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingApiInstanceTargetField) SetIsOrganizationWide(isOrganizationWide bool) {
	f.IsOrganizationWide = isOrganizationWide
	f.require(fieldMappingApiInstanceTargetFieldFieldIsOrganizationWide)
}

func (f *FieldMappingApiInstanceTargetField) UnmarshalJSON(data []byte) error {
	type unmarshaler FieldMappingApiInstanceTargetField
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FieldMappingApiInstanceTargetField(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FieldMappingApiInstanceTargetField) MarshalJSON() ([]byte, error) {
	type embed FieldMappingApiInstanceTargetField
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FieldMappingApiInstanceTargetField) String() string {
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	fieldMappingInstanceResponseFieldModel    = big.NewInt(1 << 0)
	fieldMappingInstanceResponseFieldWarnings = big.NewInt(1 << 1)
	fieldMappingInstanceResponseFieldErrors   = big.NewInt(1 << 2)
	fieldMappingInstanceResponseFieldLogs     = big.NewInt(1 << 3)
)

type FieldMappingInstanceResponse struct {
	Model    *FieldMappingApiInstance    `json:"model" url:"model"`
	Warnings []*WarningValidationProblem `json:"warnings" url:"warnings"`
	Errors   []*ErrorValidationProblem   `json:"errors" url:"errors"`
	Logs     []*DebugModeLog             `json:"logs,omitempty" url:"logs,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *FieldMappingInstanceResponse) GetModel() *FieldMappingApiInstance {
	if f == nil {
		return nil
	}
	return f.Model
}

func (f *FieldMappingInstanceResponse) GetWarnings() []*WarningValidationProblem {
	if f == nil {
		return nil
	}
	return f.Warnings
}

func (f *FieldMappingInstanceResponse) GetErrors() []*ErrorValidationProblem {
	if f == nil {
		return nil
	}
	return f.Errors
}

func (f *FieldMappingInstanceResponse) GetLogs() []*DebugModeLog {
	if f == nil {
		return nil
	}
	return f.Logs
}

func (f *FieldMappingInstanceResponse) GetExtraProperties() map[string]interface{} {
	return f.extraProperties
}

func (f *FieldMappingInstanceResponse) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetModel sets the Model field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingInstanceResponse) SetModel(model *FieldMappingApiInstance) {
	f.Model = model
	f.require(fieldMappingInstanceResponseFieldModel)
}

// SetWarnings sets the Warnings field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingInstanceResponse) SetWarnings(warnings []*WarningValidationProblem) {
	f.Warnings = warnings
	f.require(fieldMappingInstanceResponseFieldWarnings)
}

// SetErrors sets the Errors field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingInstanceResponse) SetErrors(errors []*ErrorValidationProblem) {
	f.Errors = errors
	f.require(fieldMappingInstanceResponseFieldErrors)
}

// SetLogs sets the Logs field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *FieldMappingInstanceResponse) SetLogs(logs []*DebugModeLog) {
	f.Logs = logs
	f.require(fieldMappingInstanceResponseFieldLogs)
}

func (f *FieldMappingInstanceResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler FieldMappingInstanceResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = FieldMappingInstanceResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *FieldMappingInstanceResponse) MarshalJSON() ([]byte, error) {
	type embed FieldMappingInstanceResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *FieldMappingInstanceResponse) String() string {
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	remoteEndpointInfoFieldMethod             = big.NewInt(1 << 0)
	remoteEndpointInfoFieldUrlPath            = big.NewInt(1 << 1)
	remoteEndpointInfoFieldFieldTraversalPath = big.NewInt(1 << 2)
)

type RemoteEndpointInfo struct {
	Method             string        `json:"method" url:"method"`
	UrlPath            string        `json:"url_path" url:"url_path"`
	FieldTraversalPath []interface{} `json:"field_traversal_path" url:"field_traversal_path"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RemoteEndpointInfo) GetMethod() string {
	if r == nil {
		return ""
	}
	return r.Method
}

func (r *RemoteEndpointInfo) GetUrlPath() string {
	if r == nil {
		return ""
	}
	return r.UrlPath
}

func (r *RemoteEndpointInfo) GetFieldTraversalPath() []interface{} {
	if r == nil {
		return nil
	}
	return r.FieldTraversalPath
}

func (r *RemoteEndpointInfo) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RemoteEndpointInfo) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetMethod sets the Method field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteEndpointInfo) SetMethod(method string) {
	r.Method = method
	r.require(remoteEndpointInfoFieldMethod)
}

// SetUrlPath sets the UrlPath field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteEndpointInfo) SetUrlPath(urlPath string) {
	r.UrlPath = urlPath
	r.require(remoteEndpointInfoFieldUrlPath)
}

// SetFieldTraversalPath sets the FieldTraversalPath field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteEndpointInfo) SetFieldTraversalPath(fieldTraversalPath []interface{}) {
	r.FieldTraversalPath = fieldTraversalPath
	r.require(remoteEndpointInfoFieldFieldTraversalPath)
}

func (r *RemoteEndpointInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler RemoteEndpointInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RemoteEndpointInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RemoteEndpointInfo) MarshalJSON() ([]byte, error) {
	type embed RemoteEndpointInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RemoteEndpointInfo) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	remoteFieldApiFieldSchema             = big.NewInt(1 << 0)
	remoteFieldApiFieldRemoteKeyName      = big.NewInt(1 << 1)
	remoteFieldApiFieldRemoteEndpointInfo = big.NewInt(1 << 2)
	remoteFieldApiFieldExampleValues      = big.NewInt(1 << 3)
	remoteFieldApiFieldAdvancedMetadata   = big.NewInt(1 << 4)
	remoteFieldApiFieldCoverage           = big.NewInt(1 << 5)
)

type RemoteFieldApi struct {
	Schema             map[string]interface{}  `json:"schema" url:"schema"`
	RemoteKeyName      string                  `json:"remote_key_name" url:"remote_key_name"`
	RemoteEndpointInfo *RemoteEndpointInfo     `json:"remote_endpoint_info" url:"remote_endpoint_info"`
	ExampleValues      []interface{}           `json:"example_values,omitempty" url:"example_values,omitempty"`
	AdvancedMetadata   *AdvancedMetadata       `json:"advanced_metadata,omitempty" url:"advanced_metadata,omitempty"`
	Coverage           *RemoteFieldApiCoverage `json:"coverage,omitempty" url:"coverage,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RemoteFieldApi) GetSchema() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.Schema
}

func (r *RemoteFieldApi) GetRemoteKeyName() string {
	if r == nil {
		return ""
	}
	return r.RemoteKeyName
}

func (r *RemoteFieldApi) GetRemoteEndpointInfo() *RemoteEndpointInfo {
	if r == nil {
		return nil
	}
	return r.RemoteEndpointInfo
}

func (r *RemoteFieldApi) GetExampleValues() []interface{} {
	if r == nil {
		return nil
	}
	return r.ExampleValues
}

func (r *RemoteFieldApi) GetAdvancedMetadata() *AdvancedMetadata {
	if r == nil {
		return nil
	}
	return r.AdvancedMetadata
}

func (r *RemoteFieldApi) GetCoverage() *RemoteFieldApiCoverage {
	if r == nil {
		return nil
	}
	return r.Coverage
}

func (r *RemoteFieldApi) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RemoteFieldApi) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetSchema sets the Schema field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldApi) SetSchema(schema map[string]interface{}) {
	r.Schema = schema
	r.require(remoteFieldApiFieldSchema)
}

// SetRemoteKeyName sets the RemoteKeyName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldApi) SetRemoteKeyName(remoteKeyName string) {
	r.RemoteKeyName = remoteKeyName
	r.require(remoteFieldApiFieldRemoteKeyName)
}

// SetRemoteEndpointInfo sets the RemoteEndpointInfo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldApi) SetRemoteEndpointInfo(remoteEndpointInfo *RemoteEndpointInfo) {
	r.RemoteEndpointInfo = remoteEndpointInfo
	r.require(remoteFieldApiFieldRemoteEndpointInfo)
}

// SetExampleValues sets the ExampleValues field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldApi) SetExampleValues(exampleValues []interface{}) {
	r.ExampleValues = exampleValues
	r.require(remoteFieldApiFieldExampleValues)
}

// SetAdvancedMetadata sets the AdvancedMetadata field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldApi) SetAdvancedMetadata(advancedMetadata *AdvancedMetadata) {
	r.AdvancedMetadata = advancedMetadata
	r.require(remoteFieldApiFieldAdvancedMetadata)
}

// SetCoverage sets the Coverage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldApi) SetCoverage(coverage *RemoteFieldApiCoverage) {
	r.Coverage = coverage
	r.require(remoteFieldApiFieldCoverage)
}

func (r *RemoteFieldApi) UnmarshalJSON(data []byte) error {
	type unmarshaler RemoteFieldApi
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RemoteFieldApi(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RemoteFieldApi) MarshalJSON() ([]byte, error) {
	type embed RemoteFieldApi
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RemoteFieldApi) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type RemoteFieldApiCoverage struct {
	Integer int
	Double  float64

	typ string
}

func (r *RemoteFieldApiCoverage) GetInteger() int {
	if r == nil {
		return 0
	}
	return r.Integer
}

func (r *RemoteFieldApiCoverage) GetDouble() float64 {
	if r == nil {
		return 0
	}
	return r.Double
}

func (r *RemoteFieldApiCoverage) UnmarshalJSON(data []byte) error {
	var valueInteger int
	if err := json.Unmarshal(data, &valueInteger); err == nil {
		r.typ = "Integer"
		r.Integer = valueInteger
		return nil
	}
	var valueDouble float64
	if err := json.Unmarshal(data, &valueDouble); err == nil {
		r.typ = "Double"
		r.Double = valueDouble
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, r)
}

func (r RemoteFieldApiCoverage) MarshalJSON() ([]byte, error) {
	if r.typ == "Integer" || r.Integer != 0 {
		return json.Marshal(r.Integer)
	}
	if r.typ == "Double" || r.Double != 0 {
		return json.Marshal(r.Double)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", r)
}

type RemoteFieldApiCoverageVisitor interface {
	VisitInteger(int) error
	VisitDouble(float64) error
}

func (r *RemoteFieldApiCoverage) Accept(visitor RemoteFieldApiCoverageVisitor) error {
	if r.typ == "Integer" || r.Integer != 0 {
		return visitor.VisitInteger(r.Integer)
	}
	if r.typ == "Double" || r.Double != 0 {
		return visitor.VisitDouble(r.Double)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", r)
}

var (
	remoteFieldApiResponseFieldActivity           = big.NewInt(1 << 0)
	remoteFieldApiResponseFieldApplication        = big.NewInt(1 << 1)
	remoteFieldApiResponseFieldAttachment         = big.NewInt(1 << 2)
	remoteFieldApiResponseFieldCandidate          = big.NewInt(1 << 3)
	remoteFieldApiResponseFieldDepartment         = big.NewInt(1 << 4)
	remoteFieldApiResponseFieldEeoc               = big.NewInt(1 << 5)
	remoteFieldApiResponseFieldScheduledInterview = big.NewInt(1 << 6)
	remoteFieldApiResponseFieldJob                = big.NewInt(1 << 7)
	remoteFieldApiResponseFieldJobPosting         = big.NewInt(1 << 8)
	remoteFieldApiResponseFieldJobInterviewStage  = big.NewInt(1 << 9)
	remoteFieldApiResponseFieldOffer              = big.NewInt(1 << 10)
	remoteFieldApiResponseFieldOffice             = big.NewInt(1 << 11)
	remoteFieldApiResponseFieldRejectReason       = big.NewInt(1 << 12)
	remoteFieldApiResponseFieldScorecard          = big.NewInt(1 << 13)
	remoteFieldApiResponseFieldTag                = big.NewInt(1 << 14)
	remoteFieldApiResponseFieldRemoteUser         = big.NewInt(1 << 15)
)

type RemoteFieldApiResponse struct {
	Activity           []*RemoteFieldApi `json:"Activity,omitempty" url:"Activity,omitempty"`
	Application        []*RemoteFieldApi `json:"Application,omitempty" url:"Application,omitempty"`
	Attachment         []*RemoteFieldApi `json:"Attachment,omitempty" url:"Attachment,omitempty"`
	Candidate          []*RemoteFieldApi `json:"Candidate,omitempty" url:"Candidate,omitempty"`
	Department         []*RemoteFieldApi `json:"Department,omitempty" url:"Department,omitempty"`
	Eeoc               []*RemoteFieldApi `json:"EEOC,omitempty" url:"EEOC,omitempty"`
	ScheduledInterview []*RemoteFieldApi `json:"ScheduledInterview,omitempty" url:"ScheduledInterview,omitempty"`
	Job                []*RemoteFieldApi `json:"Job,omitempty" url:"Job,omitempty"`
	JobPosting         []*RemoteFieldApi `json:"JobPosting,omitempty" url:"JobPosting,omitempty"`
	JobInterviewStage  []*RemoteFieldApi `json:"JobInterviewStage,omitempty" url:"JobInterviewStage,omitempty"`
	Offer              []*RemoteFieldApi `json:"Offer,omitempty" url:"Offer,omitempty"`
	Office             []*RemoteFieldApi `json:"Office,omitempty" url:"Office,omitempty"`
	RejectReason       []*RemoteFieldApi `json:"RejectReason,omitempty" url:"RejectReason,omitempty"`
	Scorecard          []*RemoteFieldApi `json:"Scorecard,omitempty" url:"Scorecard,omitempty"`
	Tag                []*RemoteFieldApi `json:"Tag,omitempty" url:"Tag,omitempty"`
	RemoteUser         []*RemoteFieldApi `json:"RemoteUser,omitempty" url:"RemoteUser,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RemoteFieldApiResponse) GetActivity() []*RemoteFieldApi {
	if r == nil {
		return nil
	}
	return r.Activity
}

func (r *RemoteFieldApiResponse) GetApplication() []*RemoteFieldApi {
	if r == nil {
		return nil
	}
	return r.Application
}

func (r *RemoteFieldApiResponse) GetAttachment() []*RemoteFieldApi {
	if r == nil {
		return nil
	}
	return r.Attachment
}

func (r *RemoteFieldApiResponse) GetCandidate() []*RemoteFieldApi {
	if r == nil {
		return nil
	}
	return r.Candidate
}

func (r *RemoteFieldApiResponse) GetDepartment() []*RemoteFieldApi {
	if r == nil {
		return nil
	}
	return r.Department
}

func (r *RemoteFieldApiResponse) GetEeoc() []*RemoteFieldApi {
	if r == nil {
		return nil
	}
	return r.Eeoc
}

func (r *RemoteFieldApiResponse) GetScheduledInterview() []*RemoteFieldApi {
	if r == nil {
		return nil
	}
	return r.ScheduledInterview
}

func (r *RemoteFieldApiResponse) GetJob() []*RemoteFieldApi {
	if r == nil {
		return nil
	}
	return r.Job
}

func (r *RemoteFieldApiResponse) GetJobPosting() []*RemoteFieldApi {
	if r == nil {
		return nil
	}
	return r.JobPosting
}

func (r *RemoteFieldApiResponse) GetJobInterviewStage() []*RemoteFieldApi {
	if r == nil {
		return nil
	}
	return r.JobInterviewStage
}

func (r *RemoteFieldApiResponse) GetOffer() []*RemoteFieldApi {
	if r == nil {
		return nil
	}
	return r.Offer
}

func (r *RemoteFieldApiResponse) GetOffice() []*RemoteFieldApi {
	if r == nil {
		return nil
	}
	return r.Office
}

func (r *RemoteFieldApiResponse) GetRejectReason() []*RemoteFieldApi {
	if r == nil {
		return nil
	}
	return r.RejectReason
}

func (r *RemoteFieldApiResponse) GetScorecard() []*RemoteFieldApi {
	if r == nil {
		return nil
	}
	return r.Scorecard
}

func (r *RemoteFieldApiResponse) GetTag() []*RemoteFieldApi {
	if r == nil {
		return nil
	}
	return r.Tag
}

func (r *RemoteFieldApiResponse) GetRemoteUser() []*RemoteFieldApi {
	if r == nil {
		return nil
	}
	return r.RemoteUser
}

func (r *RemoteFieldApiResponse) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RemoteFieldApiResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetActivity sets the Activity field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldApiResponse) SetActivity(activity []*RemoteFieldApi) {
	r.Activity = activity
	r.require(remoteFieldApiResponseFieldActivity)
}

// SetApplication sets the Application field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldApiResponse) SetApplication(application []*RemoteFieldApi) {
	r.Application = application
	r.require(remoteFieldApiResponseFieldApplication)
}

// SetAttachment sets the Attachment field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldApiResponse) SetAttachment(attachment []*RemoteFieldApi) {
	r.Attachment = attachment
	r.require(remoteFieldApiResponseFieldAttachment)
}

// SetCandidate sets the Candidate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldApiResponse) SetCandidate(candidate []*RemoteFieldApi) {
	r.Candidate = candidate
	r.require(remoteFieldApiResponseFieldCandidate)
}

// SetDepartment sets the Department field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldApiResponse) SetDepartment(department []*RemoteFieldApi) {
	r.Department = department
	r.require(remoteFieldApiResponseFieldDepartment)
}

// SetEeoc sets the Eeoc field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldApiResponse) SetEeoc(eeoc []*RemoteFieldApi) {
	r.Eeoc = eeoc
	r.require(remoteFieldApiResponseFieldEeoc)
}

// SetScheduledInterview sets the ScheduledInterview field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldApiResponse) SetScheduledInterview(scheduledInterview []*RemoteFieldApi) {
	r.ScheduledInterview = scheduledInterview
	r.require(remoteFieldApiResponseFieldScheduledInterview)
}

// SetJob sets the Job field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldApiResponse) SetJob(job []*RemoteFieldApi) {
	r.Job = job
	r.require(remoteFieldApiResponseFieldJob)
}

// SetJobPosting sets the JobPosting field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldApiResponse) SetJobPosting(jobPosting []*RemoteFieldApi) {
	r.JobPosting = jobPosting
	r.require(remoteFieldApiResponseFieldJobPosting)
}

// SetJobInterviewStage sets the JobInterviewStage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldApiResponse) SetJobInterviewStage(jobInterviewStage []*RemoteFieldApi) {
	r.JobInterviewStage = jobInterviewStage
	r.require(remoteFieldApiResponseFieldJobInterviewStage)
}

// SetOffer sets the Offer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldApiResponse) SetOffer(offer []*RemoteFieldApi) {
	r.Offer = offer
	r.require(remoteFieldApiResponseFieldOffer)
}

// SetOffice sets the Office field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldApiResponse) SetOffice(office []*RemoteFieldApi) {
	r.Office = office
	r.require(remoteFieldApiResponseFieldOffice)
}

// SetRejectReason sets the RejectReason field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldApiResponse) SetRejectReason(rejectReason []*RemoteFieldApi) {
	r.RejectReason = rejectReason
	r.require(remoteFieldApiResponseFieldRejectReason)
}

// SetScorecard sets the Scorecard field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldApiResponse) SetScorecard(scorecard []*RemoteFieldApi) {
	r.Scorecard = scorecard
	r.require(remoteFieldApiResponseFieldScorecard)
}

// SetTag sets the Tag field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldApiResponse) SetTag(tag []*RemoteFieldApi) {
	r.Tag = tag
	r.require(remoteFieldApiResponseFieldTag)
}

// SetRemoteUser sets the RemoteUser field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RemoteFieldApiResponse) SetRemoteUser(remoteUser []*RemoteFieldApi) {
	r.RemoteUser = remoteUser
	r.require(remoteFieldApiResponseFieldRemoteUser)
}

func (r *RemoteFieldApiResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RemoteFieldApiResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RemoteFieldApiResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RemoteFieldApiResponse) MarshalJSON() ([]byte, error) {
	type embed RemoteFieldApiResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RemoteFieldApiResponse) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}
