// Code generated by Fern. DO NOT EDIT.

package crm

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/merge-api/merge-go-client/v2/internal"
)

type EndUserDetailsRequest struct {
	// Your end user's email address. This is purely for identification purposes - setting this value will not cause any emails to be sent.
	EndUserEmailAddress string `json:"end_user_email_address" url:"-"`
	// Your end user's organization.
	EndUserOrganizationName string `json:"end_user_organization_name" url:"-"`
	// This unique identifier typically represents the ID for your end user in your product's database. This value must be distinct from other Linked Accounts' unique identifiers.
	EndUserOriginId string `json:"end_user_origin_id" url:"-"`
	// The integration categories to show in Merge Link.
	Categories []CategoriesEnum `json:"categories,omitempty" url:"-"`
	// The slug of a specific pre-selected integration for this linking flow token. For examples of slugs, see https://docs.merge.dev/guides/merge-link/single-integration/.
	Integration *string `json:"integration,omitempty" url:"-"`
	// An integer number of minutes between [30, 720 or 10080 if for a Magic Link URL] for how long this token is valid. Defaults to 30.
	LinkExpiryMins *int `json:"link_expiry_mins,omitempty" url:"-"`
	// Whether to generate a Magic Link URL. Defaults to false. For more information on Magic Link, see https://merge.dev/blog/integrations-fast-say-hello-to-magic-link.
	ShouldCreateMagicLinkUrl *bool `json:"should_create_magic_link_url,omitempty" url:"-"`
	// Whether to generate a Magic Link URL on the Admin Needed screen during the linking flow. Defaults to false. For more information on Magic Link, see https://merge.dev/blog/integrations-fast-say-hello-to-magic-link.
	HideAdminMagicLink *bool `json:"hide_admin_magic_link,omitempty" url:"-"`
	// An array of objects to specify the models and fields that will be disabled for a given Linked Account. Each object uses model_id, enabled_actions, and disabled_fields to specify the model, method, and fields that are scoped for a given Linked Account.
	CommonModels []*CommonModelScopesBodyRequest `json:"common_models,omitempty" url:"-"`
	// When creating a Link Token, you can set permissions for Common Models that will apply to the account that is going to be linked. Any model or field not specified in link token payload will default to existing settings.
	CategoryCommonModelScopes map[string][]*IndividualCommonModelScopeDeserializerRequest `json:"category_common_model_scopes,omitempty" url:"-"`
	// The following subset of IETF language tags can be used to configure localization.
	//
	// * `en` - en
	// * `de` - de
	Language *LanguageEnum `json:"language,omitempty" url:"-"`
	// The boolean that indicates whether initial, periodic, and force syncs will be disabled.
	AreSyncsDisabled *bool `json:"are_syncs_disabled,omitempty" url:"-"`
	// A JSON object containing integration-specific configuration options.
	IntegrationSpecificConfig map[string]interface{} `json:"integration_specific_config,omitempty" url:"-"`
}

type CommonModelScopesBodyRequest struct {
	ModelId        string               `json:"model_id" url:"model_id"`
	EnabledActions []EnabledActionsEnum `json:"enabled_actions" url:"enabled_actions"`
	DisabledFields []string             `json:"disabled_fields" url:"disabled_fields"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CommonModelScopesBodyRequest) GetModelId() string {
	if c == nil {
		return ""
	}
	return c.ModelId
}

func (c *CommonModelScopesBodyRequest) GetEnabledActions() []EnabledActionsEnum {
	if c == nil {
		return nil
	}
	return c.EnabledActions
}

func (c *CommonModelScopesBodyRequest) GetDisabledFields() []string {
	if c == nil {
		return nil
	}
	return c.DisabledFields
}

func (c *CommonModelScopesBodyRequest) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CommonModelScopesBodyRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CommonModelScopesBodyRequest
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CommonModelScopesBodyRequest(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CommonModelScopesBodyRequest) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// * `READ` - READ
// * `WRITE` - WRITE
type EnabledActionsEnum string

const (
	EnabledActionsEnumRead  EnabledActionsEnum = "READ"
	EnabledActionsEnumWrite EnabledActionsEnum = "WRITE"
)

func NewEnabledActionsEnumFromString(s string) (EnabledActionsEnum, error) {
	switch s {
	case "READ":
		return EnabledActionsEnumRead, nil
	case "WRITE":
		return EnabledActionsEnumWrite, nil
	}
	var t EnabledActionsEnum
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (e EnabledActionsEnum) Ptr() *EnabledActionsEnum {
	return &e
}

// * `en` - en
// * `de` - de
type LanguageEnum string

const (
	LanguageEnumEn LanguageEnum = "en"
	LanguageEnumDe LanguageEnum = "de"
)

func NewLanguageEnumFromString(s string) (LanguageEnum, error) {
	switch s {
	case "en":
		return LanguageEnumEn, nil
	case "de":
		return LanguageEnumDe, nil
	}
	var t LanguageEnum
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l LanguageEnum) Ptr() *LanguageEnum {
	return &l
}

type LinkToken struct {
	LinkToken       string  `json:"link_token" url:"link_token"`
	IntegrationName *string `json:"integration_name,omitempty" url:"integration_name,omitempty"`
	MagicLinkUrl    *string `json:"magic_link_url,omitempty" url:"magic_link_url,omitempty"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *LinkToken) GetLinkToken() string {
	if l == nil {
		return ""
	}
	return l.LinkToken
}

func (l *LinkToken) GetIntegrationName() *string {
	if l == nil {
		return nil
	}
	return l.IntegrationName
}

func (l *LinkToken) GetMagicLinkUrl() *string {
	if l == nil {
		return nil
	}
	return l.MagicLinkUrl
}

func (l *LinkToken) GetExtraProperties() map[string]interface{} {
	return l.extraProperties
}

func (l *LinkToken) UnmarshalJSON(data []byte) error {
	type unmarshaler LinkToken
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = LinkToken(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *LinkToken) String() string {
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}
