// Code generated by Fern. DO NOT EDIT.

package associations

import (
	context "context"
	core "github.com/merge-api/merge-go-client/v2/core"
	crm "github.com/merge-api/merge-go-client/v2/crm"
	internal "github.com/merge-api/merge-go-client/v2/internal"
	option "github.com/merge-api/merge-go-client/v2/option"
	http "net/http"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

func (r *RawClient) CustomObjectClassesCustomObjectsAssociationsUpdate(
	ctx context.Context,
	sourceClassId string,
	sourceObjectId string,
	targetClassId string,
	targetObjectId string,
	associationTypeId string,
	request *crm.CustomObjectClassesCustomObjectsAssociationsUpdateRequest,
	opts ...option.RequestOption,
) (*core.Response[*crm.Association], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/crm/v1/custom-object-classes/%v/custom-objects/%v/associations/%v/%v/%v",
		sourceClassId,
		sourceObjectId,
		targetClassId,
		targetObjectId,
		associationTypeId,
	)
	queryParams, err := internal.QueryValues(request)
	if err != nil {
		return nil, err
	}
	if len(queryParams) > 0 {
		endpointURL += "?" + queryParams.Encode()
	}
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *crm.Association
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPut,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*crm.Association]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
