// Code generated by Fern. DO NOT EDIT.

package ticketing

import (
	fmt "fmt"
	big "math/big"
	time "time"
)

var (
	usersListRequestFieldCreatedAfter       = big.NewInt(1 << 0)
	usersListRequestFieldCreatedBefore      = big.NewInt(1 << 1)
	usersListRequestFieldCursor             = big.NewInt(1 << 2)
	usersListRequestFieldEmailAddress       = big.NewInt(1 << 3)
	usersListRequestFieldExpand             = big.NewInt(1 << 4)
	usersListRequestFieldIncludeDeletedData = big.NewInt(1 << 5)
	usersListRequestFieldIncludeRemoteData  = big.NewInt(1 << 6)
	usersListRequestFieldIncludeShellData   = big.NewInt(1 << 7)
	usersListRequestFieldModifiedAfter      = big.NewInt(1 << 8)
	usersListRequestFieldModifiedBefore     = big.NewInt(1 << 9)
	usersListRequestFieldPageSize           = big.NewInt(1 << 10)
	usersListRequestFieldRemoteId           = big.NewInt(1 << 11)
	usersListRequestFieldTeam               = big.NewInt(1 << 12)
)

type UsersListRequest struct {
	// If provided, will only return objects created after this datetime.
	CreatedAfter *time.Time `json:"-" url:"created_after,omitempty"`
	// If provided, will only return objects created before this datetime.
	CreatedBefore *time.Time `json:"-" url:"created_before,omitempty"`
	// The pagination cursor value.
	Cursor *string `json:"-" url:"cursor,omitempty"`
	// If provided, will only return users with emails equal to this value (case insensitive).
	EmailAddress *string `json:"-" url:"email_address,omitempty"`
	// Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
	Expand []*UsersListRequestExpandItem `json:"-" url:"expand,omitempty"`
	// Indicates whether or not this object has been deleted in the third party platform. Full coverage deletion detection is a premium add-on. Native deletion detection is offered for free with limited coverage. [Learn more](https://docs.merge.dev/integrations/hris/supported-features/).
	IncludeDeletedData *bool `json:"-" url:"include_deleted_data,omitempty"`
	// Whether to include the original data Merge fetched from the third-party to produce these models.
	IncludeRemoteData *bool `json:"-" url:"include_remote_data,omitempty"`
	// Whether to include shell records. Shell records are empty records (they may contain some metadata but all other fields are null).
	IncludeShellData *bool `json:"-" url:"include_shell_data,omitempty"`
	// If provided, only objects synced by Merge after this date time will be returned.
	ModifiedAfter *time.Time `json:"-" url:"modified_after,omitempty"`
	// If provided, only objects synced by Merge before this date time will be returned.
	ModifiedBefore *time.Time `json:"-" url:"modified_before,omitempty"`
	// Number of results to return per page.
	PageSize *int `json:"-" url:"page_size,omitempty"`
	// The API provider's ID for the given object.
	RemoteId *string `json:"-" url:"remote_id,omitempty"`
	// If provided, will only return users matching in this team.
	Team *string `json:"-" url:"team,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UsersListRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetCreatedAfter sets the CreatedAfter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UsersListRequest) SetCreatedAfter(createdAfter *time.Time) {
	u.CreatedAfter = createdAfter
	u.require(usersListRequestFieldCreatedAfter)
}

// SetCreatedBefore sets the CreatedBefore field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UsersListRequest) SetCreatedBefore(createdBefore *time.Time) {
	u.CreatedBefore = createdBefore
	u.require(usersListRequestFieldCreatedBefore)
}

// SetCursor sets the Cursor field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UsersListRequest) SetCursor(cursor *string) {
	u.Cursor = cursor
	u.require(usersListRequestFieldCursor)
}

// SetEmailAddress sets the EmailAddress field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UsersListRequest) SetEmailAddress(emailAddress *string) {
	u.EmailAddress = emailAddress
	u.require(usersListRequestFieldEmailAddress)
}

// SetExpand sets the Expand field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UsersListRequest) SetExpand(expand []*UsersListRequestExpandItem) {
	u.Expand = expand
	u.require(usersListRequestFieldExpand)
}

// SetIncludeDeletedData sets the IncludeDeletedData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UsersListRequest) SetIncludeDeletedData(includeDeletedData *bool) {
	u.IncludeDeletedData = includeDeletedData
	u.require(usersListRequestFieldIncludeDeletedData)
}

// SetIncludeRemoteData sets the IncludeRemoteData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UsersListRequest) SetIncludeRemoteData(includeRemoteData *bool) {
	u.IncludeRemoteData = includeRemoteData
	u.require(usersListRequestFieldIncludeRemoteData)
}

// SetIncludeShellData sets the IncludeShellData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UsersListRequest) SetIncludeShellData(includeShellData *bool) {
	u.IncludeShellData = includeShellData
	u.require(usersListRequestFieldIncludeShellData)
}

// SetModifiedAfter sets the ModifiedAfter field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UsersListRequest) SetModifiedAfter(modifiedAfter *time.Time) {
	u.ModifiedAfter = modifiedAfter
	u.require(usersListRequestFieldModifiedAfter)
}

// SetModifiedBefore sets the ModifiedBefore field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UsersListRequest) SetModifiedBefore(modifiedBefore *time.Time) {
	u.ModifiedBefore = modifiedBefore
	u.require(usersListRequestFieldModifiedBefore)
}

// SetPageSize sets the PageSize field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UsersListRequest) SetPageSize(pageSize *int) {
	u.PageSize = pageSize
	u.require(usersListRequestFieldPageSize)
}

// SetRemoteId sets the RemoteId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UsersListRequest) SetRemoteId(remoteId *string) {
	u.RemoteId = remoteId
	u.require(usersListRequestFieldRemoteId)
}

// SetTeam sets the Team field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UsersListRequest) SetTeam(team *string) {
	u.Team = team
	u.require(usersListRequestFieldTeam)
}

var (
	usersRetrieveRequestFieldExpand            = big.NewInt(1 << 0)
	usersRetrieveRequestFieldIncludeRemoteData = big.NewInt(1 << 1)
	usersRetrieveRequestFieldIncludeShellData  = big.NewInt(1 << 2)
)

type UsersRetrieveRequest struct {
	// Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces.
	Expand []*UsersRetrieveRequestExpandItem `json:"-" url:"expand,omitempty"`
	// Whether to include the original data Merge fetched from the third-party to produce these models.
	IncludeRemoteData *bool `json:"-" url:"include_remote_data,omitempty"`
	// Whether to include shell records. Shell records are empty records (they may contain some metadata but all other fields are null).
	IncludeShellData *bool `json:"-" url:"include_shell_data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UsersRetrieveRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetExpand sets the Expand field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UsersRetrieveRequest) SetExpand(expand []*UsersRetrieveRequestExpandItem) {
	u.Expand = expand
	u.require(usersRetrieveRequestFieldExpand)
}

// SetIncludeRemoteData sets the IncludeRemoteData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UsersRetrieveRequest) SetIncludeRemoteData(includeRemoteData *bool) {
	u.IncludeRemoteData = includeRemoteData
	u.require(usersRetrieveRequestFieldIncludeRemoteData)
}

// SetIncludeShellData sets the IncludeShellData field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UsersRetrieveRequest) SetIncludeShellData(includeShellData *bool) {
	u.IncludeShellData = includeShellData
	u.require(usersRetrieveRequestFieldIncludeShellData)
}

type UsersListRequestExpandItem string

const (
	UsersListRequestExpandItemRoles UsersListRequestExpandItem = "roles"
	UsersListRequestExpandItemTeams UsersListRequestExpandItem = "teams"
)

func NewUsersListRequestExpandItemFromString(s string) (UsersListRequestExpandItem, error) {
	switch s {
	case "roles":
		return UsersListRequestExpandItemRoles, nil
	case "teams":
		return UsersListRequestExpandItemTeams, nil
	}
	var t UsersListRequestExpandItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UsersListRequestExpandItem) Ptr() *UsersListRequestExpandItem {
	return &u
}

type UsersRetrieveRequestExpandItem string

const (
	UsersRetrieveRequestExpandItemRoles UsersRetrieveRequestExpandItem = "roles"
	UsersRetrieveRequestExpandItemTeams UsersRetrieveRequestExpandItem = "teams"
)

func NewUsersRetrieveRequestExpandItemFromString(s string) (UsersRetrieveRequestExpandItem, error) {
	switch s {
	case "roles":
		return UsersRetrieveRequestExpandItemRoles, nil
	case "teams":
		return UsersRetrieveRequestExpandItemTeams, nil
	}
	var t UsersRetrieveRequestExpandItem
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UsersRetrieveRequestExpandItem) Ptr() *UsersRetrieveRequestExpandItem {
	return &u
}
