// Code generated by Fern. DO NOT EDIT.

package projects

import (
	context "context"
	accounting "github.com/merge-api/merge-go-client/v2/accounting"
	core "github.com/merge-api/merge-go-client/v2/core"
	internal "github.com/merge-api/merge-go-client/v2/internal"
	option "github.com/merge-api/merge-go-client/v2/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Returns a list of `Project` objects.
func (c *Client) List(
	ctx context.Context,
	request *accounting.ProjectsListRequest,
	opts ...option.RequestOption,
) (*accounting.PaginatedProjectList, error) {
	response, err := c.WithRawResponse.List(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns a `Project` object with the given `id`.
func (c *Client) Retrieve(
	ctx context.Context,
	id string,
	request *accounting.ProjectsRetrieveRequest,
	opts ...option.RequestOption,
) (*accounting.Project, error) {
	response, err := c.WithRawResponse.Retrieve(
		ctx,
		id,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
